# Generated by Django 4.0.4 on 2022-05-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceTable',
            fields=[
                ('CodeSnippetID', models.AutoField(primary_key=True, serialize=False)),
                ('Tag', models.CharField(max_length=500)),
                ('Description', models.TextField()),
                ('OptChar', models.TextField()),
                ('OptInt', models.IntegerField()),
            ],
        ),
    ]
