# Generated by Django 4.0.4 on 2022-05-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippetsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSnippets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
            ],
        ),
    ]
