# Generated by Django 4.0.4 on 2022-05-31 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippetsApp', '0002_codesnippets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesnippets',
            name='Name',
        ),
        migrations.AddField(
            model_name='codesnippets',
            name='Snip',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='referencetable',
            name='snip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snippetsApp.codesnippets'),
        ),
    ]
