# Generated by Django 4.0.4 on 2022-05-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippetsApp', '0003_remove_codesnippets_name_codesnippets_snip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippets',
            name='Snip',
            field=models.TextField(blank=True),
        ),
    ]
