# Generated by Django 4.0.4 on 2022-05-31 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippetsApp', '0004_alter_codesnippets_snip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencetable',
            name='snip',
        ),
    ]
