# Generated by Django 4.0.4 on 2022-05-31 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippetsApp', '0005_remove_referencetable_snip'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencetable',
            name='snip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snippetsApp.codesnippets'),
        ),
    ]
